#lang can be "en" (english) or "fr" (french)
lang: en

updateInterval: 5000
targetFile: /path/to/overviewermap/markers.json
saveOfflinePlayers: true
offlineFile: locations.bin
tagmessages: true

#Don't send those status
hideVanishedPlayers: true
hideSneakingPlayers: false
hideInvisiblePlayers: true
hideSpectatorPlayers: true

#Send custom ID for those status
sendJSONOnVanishedPlayers: false
sendJSONOnSneakingPlayers: false
sendJSONOnInvisiblePlayers: false
sendJSONOnSpectatorPlayers: false